### ISSUE TITLE
WDInstagram Rails HW

### ISSUE THREAD

**Issue by pdoulatshahi** [ga-wdi-exercises/WDInstagram_rails#11]
Comfort level: 4/5
Completeness: 4/5

https://github.com/pdoulatshahi/wdinstagram_rails/tree/pd_solution

I'm blanking on seeding the data - not working. I am using the same seeding command as with Sinatra - just doesn't seem to be working. No CSS either. Everything else seems to be working.

User stories for blog - as a user I should be able to:
1. view all blog posts on one page;
2. view just one specific blog post;
3. add a new blog post;
4. edit/update a blog post from that blog post's page;
5. delete a blog post from either the all posts page or the specific blog post's page.

**Comment by RobertAKARobin** [comment]
Can you be more specific about how it isn't working? Are you getting an error, or is it just that nothing's happening? Remember that `rake db:seed` doesn't show anything in the terminal when it's successful.
