### ISSUE TITLE
WDI Instagram Rails

### ISSUE THREAD

**Issue by silviascript** [ga-wdi-exercises/WDInstagram_rails#18]
https://github.com/siltastic/wdi-instagram

Comfort Level: 3/5
Completeness: 5/5

This was a challenging assignment; however, I have a better understanding of the structure and placements of certain information. At first, I was going to work with what Andy taught us  (the setup), but decided to use Jesse's way. Then incorporated the lessons about routes and conversions from Andy. It was hard, yet fun!

User Stories: As a user, I should be able to ...
- Add a blog post in order to share information.
- Add a photo(s) in order to share photographic information.
- Edit a blog post in order to correct information.
- Know how to navigate the blog site in order to start posting posts.

My blog will be about French toast, my guilty pleasure.

**Comment by RobertAKARobin** [comment]
Woo! I'm glad you got it, and even more, I'm glad you enjoy challenges!
