### ISSUE TITLE
wdinstagram on rails

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/WDInstagram_rails#22]
comfortLevel: 2
completeness: 2
link to repo: https://github.com/tomBeach/wdinstagram_tomBeach

Failures after creating/modifying files and database. Stuck on "Unable to autoload constant EntriesController..."  

user stories for blog project:
• I want to add a new blog entry with a single click to quickly get to writing the entry
• I want to save my entry via save button when done so my entry is preserved in the blog
• I want to be able to edit my entry via edit button so I can make corrections after saving
• I want to be able to select blog entries from selected contributors so I can follow entries I find interesting
• I want to be able to sort entries by date, topic, author so I can organize blog content
• I want to see authors, topic and date entered on each blog entry so I know what I am seeing
• I want the blog entries to be limited in length so authors are encouraged to get to the point

**Comment by RobertAKARobin** [comment]
I found it! The problem's a typo. The first line of `entries_controller` is `class ArtistsController < ApplicationController`
