### ISSUE TITLE
rachel wdinstagram

### ISSUE THREAD

**Issue by rewarren** [ga-wdi-exercises/WDInstagram_rails#27]
https://github.com/rewarren/rachel_wdinstagram

comfort: 2.7
complete 2.5..

I attempted wdinstagram at GA but had to shut down because i didn't feel like i was doing anything in the correct flow order and it became overwhelming to me. Came home and started over completely but still couldn't understand an error I received in terminal when trying to run rails server (I attached a screen shot). i received it at first while still at GA, but lo and behold it found me in a brand new rails file at home too.  at GA i thought it was because i hadn't yet created an entries_controller.rb file (i think), but this time around that particular file was already created... i was never able to go to localhost:3000...frustration won out. feel defeated 

<img width="1071" alt="screen shot 2015-07-27 at 9 57 37 pm" src="https://cloud.githubusercontent.com/assets/10967783/8921958/97aa7f50-34aa-11e5-8b35-1ab30b1b14be.png">

user stories for the blog:

as a user i want to see the most recent post at top
as a user i want to create a post
as a user i want to be able to edit a post

**Comment by RobertAKARobin** [comment]
Ah! I think the problem is your Entries controller doesn't have a title! It should start with `class EntriesController < ApplicationController`
