### ISSUE TITLE
rails/user stories

### ISSUE THREAD

**Issue by nayana487** [ga-wdi-exercises/WDInstagram_rails#31]
comfort: 4
completeness: 4.5

I'm pretty sure my code is written correctly, but for some reason some of the pages are giving me strange errors. 

https://github.com/nayana487/rails_intro

user stories for blog

As a user, I would like to see a listing of all posts. 
As a user, I would like to see an individual post. 
As a user, I would like to create a post. 
As a user, I would like to delete a post. 
As a user, I would like to edit a post.

**Comment by RobertAKARobin** [comment]
If you can be more specific about the errors, I'd be happy to take a look!

**Comment by nayana487** [comment]
You helped me with it yesterday, thanks!
