### ISSUE TITLE
SGheysens WDInstagram_rails submission

### ISSUE THREAD

**Issue by segheysens** [ga-wdi-exercises/WDInstagram_rails#41]
Link to WDInstagram Rails app: https://github.com/segheysens/WDInstagram_rails

Blog application User stories:
- As a user, I should be able to create/edit/update/destroy a post
- As a user, I should be able to comment on posts
  (Our class hasn't really been introduced to the assignment yet, but I'd be happy to come back and update these once we have!)

**Comment by RobertAKARobin** [comment]
Please give me your comfort and completeness score!
